Python error in ascii encoding
Error was thrown:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc2' in position 301: ordinal not in range(128)

Turns out the strings are managed as ascii by default so need to encode
them ast utf 8 instead.